### ISSUE TITLE
reach_demo refers to motoman model that is not part of repository

### ISSUE THREAD

**Issue by rtonnaer** [ros-industrial/reach#7]
In [this xacro](https://github.com/ros-industrial/reach/blob/master/reach_demo/model/reach_study.xacro ) a robot model is referenced that is not part of this repo (`model/motoman_sia20d_macro.xacro`).

Would it be an idea to make a minor change and let it refer to: [this](https://github.com/ros-industrial/motoman/blob/kinetic-devel/motoman_sia20d_support/urdf/sia20d_macro.xacro) xacro in the  ROS-Industrial Motoman repository.

I have tested this locally and (as far as I can oversee) it seems to work fine.

**Comment by marip8** [comment]
I did that intentionally because (as of now) the Motoman packages are not released as debians for ROS Kinetic or Melodic. I opted not to make the Motoman repository a dependency of this package (i.e. via rosinstall) because it seemed a bit clunky and unnecessary compared to copying the one URDF I wanted for the demo. Once debians get released for that repository, I think it would be a good idea to remove my version of the URDF and use the official one

**Comment by gavanderhoorn** [comment]
I think the issue @rtonnaer is reporting that `reach_demo/model` does not contain your copy Michael :)

**Comment by marip8** [comment]
Ah, I see. I double-checked after I left the comment and found that the URDF had only made it into my local repository. I'll make a PR with the change (and probably a unit test to make sure it actually works this time....)

**Comment by marip8** [comment]
@rtonnaer @gavanderhoorn closing the issue because it should be addressed by #8. Thanks for bringing this to my attention
